[gauntlet]
name = 'Bletooth Manager'
description = """
Connect and disconnect bluetooth devices.
"""

[[entrypoint]]
id = 'template-view'
name = 'Bletooth Manager'
path = 'src/template-view.tsx'
type = 'view'
description = """
Bluetopth devices list
"""

[permissions.exec]
command = ["bluetoothctl"]

[[supported_system]]
os = 'linux'

# [[supported_system]]
# os = 'macos'

# [[supported_system]]
# os = 'windows'

